import csv
import os
import re


def main():
    print('-'*60)
    print('This is a conversion tool')
    print('It can copy and reproduce the table generated by AI')
    print('Instruction of use:')
    print('1. Copy and paste the table generated by AI')
    print('2. Press the Enter key')
    print('3. Input "generate"')
    print('4. Press the Enter key again')
    print('-'*60)

    user_input = []
    while True:
        line = input()
        if line.strip().lower() == 'generate':
            break
        user_input.append(line)
    user_input = '\n'.join(user_input)

    try:
        table_data = step_one_table(user_input)
        print('The complete table after parsing:')
        step_two_table(table_data)

    except Exception as e:
        print('Failed to process the table:{}'.format(e))

def step_one_table(user_input):
    lines = [line.rstrip() for line in user_input.split("\n")]
    valid_lines = []
    for line in lines:
        valid_lines.append(line)
    if not valid_lines:
        raise ValueError('No valid content has been identified')
    table_data = []
    for  line in valid_lines:
        row = [cell.strip() for cell in re.split(r"\s+", line)]
        table_data.append(row)
    return table_data


def step_two_table(table_data, output_path='Table generated for you.csv'):
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)
    f = open(output_path, 'w', encoding="utf-8-sig", newline="")
    writer = csv.writer(f)
    writer.writerows(table_data)
    f.close()
    print('The CSV file has been saved to: {}'.format(os.path.abspath(output_path)))
    print('You can open it directly with Excel/WPS')
    print('-'*60)


if __name__ == '__main__':
    main()
